name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'android'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew


    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew build
