name: Android CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'

jobs:
  build-upload:
    name: Build & Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: "adopt"
          cache: gradle
      - name: Fix gradlew permission
        run: chmod +x gradlew
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
      - name: Build with Gradle
        run: ./gradlew assembleDebug
