name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Set up Android SDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'android-sdk'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew build
